import { language } from "../app/i18n/language.ts"
import { languageSignal } from "../app/i18n/languageSignal.ts"

export function ticketCheckoutText() {
  if (languageSignal.get() === language.de) {
    return {
      title: "Kasse",
      orderSummary: "Bestellübersicht",
      noTicketsSelected: "Noch keine Tickets gewählt",
      chooseTickets: "Wähle deine gewünschten Tickets aus",
      subtotal: "Zwischensumme",
      fees: "Service- & Vorverkaufsgebühren",
      total: "Gesamtsumme (inkl. MwSt.)",
      feesIncluded: "Garantierter Endpreis inklusive aller Gebühren",
      addToCart: "In den Warenkorb",
      directCheckout: "Direkt zur Kasse",
      paymentMethods: "Zahlungsmethoden",
      supportedPaymentMethods: "Unterstützte Zahlungsmethoden",
      decreaseTicket: "Ein Ticket weniger für",
      increaseTicket: "Ein Ticket mehr für",
      ticketsSelected: "Tickets gewählt",
      tickets: "Tickets",
      perTicket: "pro Ticket",
      fromPrice: "ab",
      backToCart: "Zum Warenkorb",
      backToEvents: "Zurück zur Event-Übersicht",
      catalogUnavailable: "Der Eventkatalog ist gerade nicht verfügbar. Bitte versuche es später erneut.",
      eventNotFound: "Für diese Bestellung wurde kein Event gefunden. Bitte wähle ein Event neu aus.",
      noValidTickets: "Dein Warenkorb enthält keine gültigen Tickets. Bitte wähle ein Event neu aus.",
      contactTitle: "Kontaktdaten (Gast-Checkout)",
      contactDescription: "Kein Konto nötig – deine Tickets kommen sofort digital.",
      firstName: "Vorname",
      lastName: "Nachname",
      email: "E-Mail",
      emailHint: "An diese Adresse senden wir deine Ticketbestätigung.",
      phone: "Telefon (optional)",
      participantTitle: "Teilnehmernamen",
      participantDescription:
        "Gib für jedes Ticket den Namen der teilnehmenden Person an. Die Käuferdaten bleiben davon getrennt.",
      participant: "Teilnehmer:in",
      participantName: "Name der teilnehmenden Person",
      participantRequired: "Bitte gib für jedes Ticket einen Teilnehmernamen an.",
      ticket: "Ticket",
      payment: "Zahlung",
      paymentDescription:
        "Du wirst für die sichere Zahlung zum Zahlungsanbieter weitergeleitet. Der verbindliche Zahlungsstatus kommt anschließend vom Server zurück.",
      purchaser: "Käufer:in",
      amountDue: "Zu zahlen",
      legalBeforeTerms: "Ich akzeptiere die",
      terms: "AGB",
      legalBetweenLinks: "und habe die",
      privacy: "Datenschutzhinweise",
      legalAfterPrivacy: "gelesen.",
      submitting: "Checkout wird erstellt …",
      submit: "Weiter zur sicheren Zahlung",
      emptyCart: "Bitte wähle zuerst mindestens ein Ticket aus.",
      legalRequired: "Bitte bestätige AGB und Datenschutzhinweise.",
      checkoutFailed: "Checkout konnte nicht erstellt werden.",
      legalCta: "Jetzt kostenpflichtig buchen",
      locale: "de" as const,
    }
  }

  return {
    title: "Checkout",
    orderSummary: "Order summary",
    noTicketsSelected: "No tickets selected yet",
    chooseTickets: "Choose your tickets",
    subtotal: "Subtotal",
    fees: "Service and presale fees",
    total: "Total (including VAT)",
    feesIncluded: "Guaranteed final price including all fees",
    addToCart: "Add to cart",
    directCheckout: "Go directly to checkout",
    paymentMethods: "Payment methods",
    supportedPaymentMethods: "Supported payment methods",
    decreaseTicket: "One fewer ticket for",
    increaseTicket: "One more ticket for",
    ticketsSelected: "tickets selected",
    tickets: "tickets",
    perTicket: "per ticket",
    fromPrice: "from",
    backToCart: "Back to cart",
    backToEvents: "Back to event overview",
    catalogUnavailable: "The event catalog is currently unavailable. Please try again later.",
    eventNotFound: "No event was found for this order. Please choose an event again.",
    noValidTickets: "Your cart contains no valid tickets. Please choose an event again.",
    contactTitle: "Contact details (guest checkout)",
    contactDescription: "No account needed – your digital tickets arrive immediately.",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    emailHint: "We will send your ticket confirmation to this address.",
    phone: "Phone (optional)",
    participantTitle: "Participant names",
    participantDescription: "Enter the participant's name for each ticket. The purchaser details remain separate.",
    participant: "Participant",
    participantName: "Participant name",
    participantRequired: "Please enter a participant name for every ticket.",
    ticket: "Ticket",
    payment: "Payment",
    paymentDescription:
      "You will be redirected to the payment provider for secure payment. The binding payment status is then returned by the server.",
    purchaser: "Purchaser",
    amountDue: "Amount due",
    legalBeforeTerms: "I accept the",
    terms: "terms and conditions",
    legalBetweenLinks: "and have read the",
    privacy: "privacy notice",
    legalAfterPrivacy: ".",
    submitting: "Creating checkout …",
    submit: "Continue to secure payment",
    emptyCart: "Please select at least one ticket first.",
    legalRequired: "Please accept the terms and acknowledge the privacy notice.",
    checkoutFailed: "Checkout could not be created.",
    legalCta: "Book now with obligation to pay",
    locale: "en" as const,
  }
}
