export function ticketCheckoutText() {
  return {
    title: "Kasse",
    orderSummary: "Bestellübersicht",
    noTicketsSelected: "Noch keine Tickets gewählt",
    chooseTickets: "Wähle deine gewünschten Tickets aus",
    subtotal: "Zwischensumme",
    fees: "Service- & Vorverkaufsgebühren",
    total: "Gesamtsumme",
    feesIncluded: "Garantierter Endpreis inklusive aller Gebühren",
    addToCart: "In den Warenkorb",
    directCheckout: "Direkt zur Kasse",
    paymentMethods: "Zahlungsmethoden",
    supportedPaymentMethods: "Unterstützte Zahlungsmethoden",
    decreaseTicket: "Ein Ticket weniger für",
    increaseTicket: "Ein Ticket mehr für",
    ticketsSelected: "Tickets gewählt",
    tickets: "Tickets",
    perTicket: "pro Ticket",
    fromPrice: "ab",
    backToCart: "Zum Warenkorb",
    backToEvents: "Zurück zur Event-Übersicht",
    checkoutUnavailable: "Checkout nicht möglich",
    catalogUnavailable: "Der Eventkatalog ist gerade nicht verfügbar. Bitte versuche es später erneut.",
    eventNotFound: "Für diese Bestellung wurde kein Event gefunden. Bitte wähle ein Event neu aus.",
    noValidTickets: "Dein Warenkorb enthält keine gültigen Tickets. Bitte wähle ein Event neu aus.",
    ticketAccessInvalid: "Dieser Ticket-Link ist ungültig.",
    ticketAccessNotFound: "Die Bestellung wurde nicht gefunden.",
    contactTitle: "Kontaktdaten (Gast-Checkout)",
    contactDescription: "Kein Konto nötig – deine Tickets kommen sofort digital.",
    firstName: "Vorname",
    lastName: "Nachname",
    email: "E-Mail",
    emailHint: "An diese Adresse senden wir deine Ticketbestätigung.",
    phone: "Telefon (optional)",
    participantTitle: "Teilnehmernamen",
    participantDescription:
      "Gib für jedes Ticket den Namen der teilnehmenden Person an. Die Käuferdaten bleiben davon getrennt.",
    participant: "Teilnehmer:in",
    participantName: "Name der teilnehmenden Person",
    participantRequired: "Bitte gib für jedes Ticket einen Teilnehmernamen an.",
    ticket: "Ticket",
    payment: "Zahlung",
    paymentDescription:
      "Du wirst für die sichere Zahlung zum Zahlungsanbieter weitergeleitet. Der verbindliche Zahlungsstatus kommt anschließend vom Server zurück.",
    purchaser: "Käufer:in",
    amountDue: "Zu zahlen",
    legalBeforeTerms: "Ich akzeptiere die",
    terms: "AGB",
    legalBetweenLinks: "und habe die",
    privacy: "Datenschutzhinweise",
    legalAfterPrivacy: "gelesen.",
    submitting: "Checkout wird erstellt …",
    submit: "Weiter zur sicheren Zahlung",
    emptyCart: "Bitte wähle zuerst mindestens ein Ticket aus.",
    legalRequired: "Bitte bestätige AGB und Datenschutzhinweise.",
    requiredFields: "Fülle alle Pflichtfelder aus",
    checkoutFailed: "Checkout konnte nicht erstellt werden.",
    legalCta: "Jetzt kostenpflichtig buchen",
    locale: "de" as const,
  }
}
