// Auto-generated from src/legal/*.md by src/legalCompile.ts.
export const legalHtml = {
  impressum:
    '<blockquote>\n<p><strong>Hinweis / Disclaimer:</strong><br>Dies ist ein <strong>vorübergehendes Dummy-Impressum (Platzhalter)</strong> zu Test- und Entwicklungszwecken für die Plattform Eventoren. Die nachfolgenden Angaben stellen Musterdaten dar und werden vor dem offiziellen Launch durch die rechtsgültigen Unternehmensdaten ersetzt.</p>\n</blockquote>\n<h2>Angaben gemäß § 5 DDG (Digitale-Dienste-Gesetz)</h2>\n<p><strong>Eventoren GmbH</strong> (Musterunternehmen / Platzhalter)<br>Musterstraße 123<br>10115 Berlin<br>Deutschland  </p>\n<p><strong>Vertreten durch:</strong><br>Max Mustermann (Geschäftsführung – Platzhalter)</p>\n<h2>Kontakt</h2>\n<ul>\n<li><strong>E-Mail:</strong> <a href="mailto:partner@eventoren.de">partner@eventoren.de</a> / <a href="mailto:support@eventoren.de">support@eventoren.de</a>  </li>\n<li><strong>Telefon:</strong> +49 (0) 30 12345678 (Platzhalter)  </li>\n<li><strong>Webseite:</strong> <a href="https://eventoren.leonardomora.de">https://eventoren.leonardomora.de</a></li>\n</ul>\n<h2>Registereintrag (Musterdaten)</h2>\n<p>Eintragung im Handelsregister<br><strong>Registergericht:</strong> Amtsgericht Berlin-Charlottenburg (Platzhalter)<br><strong>Registernummer:</strong> HRB 999999 B (Platzhalter)  </p>\n<h2>Umsatzsteuer-ID (Musterdaten)</h2>\n<p>Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz:<br><strong>DE 999999999</strong> (Platzhalter)</p>\n<h2>Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV</h2>\n<p>Max Mustermann<br>Musterstraße 123<br>10115 Berlin  </p>\n<h2>EU-Streitschlichtung &amp; Verbraucherstreitbeilegung</h2>\n<p>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:<br><a href="https://ec.europa.eu/consumers/odr/">https://ec.europa.eu/consumers/odr/</a></p>\n<p>Unsere E-Mail-Adresse finden Sie oben im Impressum.</p>\n<p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>\n',
  datenschutz:
    "<h1>Datenschutzerklärung</h1>\n<p>Dies ist ein Platzhalter für die Datenschutzerklärung. Ersetze ihn vor der Veröffentlichung durch die für dein Angebot geltenden Informationen.</p>\n",
  terms:
    "<h1>Terms of Service</h1>\n<p>This placeholder is part of the public-web foundation. Replace it with the terms that apply to this service before deployment.</p>\n",
  privacy:
    "<h1>Privacy Policy</h1>\n<p>This placeholder is part of the public-web foundation. Replace it with the privacy information that applies to this service before deployment.</p>\n",
} as const
