import type { CatalogFont } from "@adaptive-ds/assets-service"

// Auto-generated by @adaptive-ds/assets-service. Do not edit.
// schema: assets.catalog.v1
// catalog-digest: d509e3374827bf5b6114b90f9a9ee725e4cadc3788f403f99aa2d909a51a994a
// renderer-version: 1
export const fontList = {} as const satisfies Record<string, CatalogFont>
