import type { FontType } from "@adaptive-ds/assets-optimizer"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const fontList = {} as const satisfies Record<string, FontType>
