import type { CatalogImage } from "@adaptive-ds/assets-service"

// Auto-generated by @adaptive-ds/assets-service. Do not edit.
// schema: assets.catalog.v1
// catalog-digest: d509e3374827bf5b6114b90f9a9ee725e4cadc3788f403f99aa2d909a51a994a
// renderer-version: 1
export const imageList = {
  "events_concert_crowd_nh78jps73cwrt9mxyc017cjvm58ez76a_card": {
    "basename": "concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 675,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a_card_v1.avif"
  },
  "events_concert_crowd_nh78jps73cwrt9mxyc017cjvm58ez76a_detail": {
    "basename": "concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 820,
      "kind": "image",
      "orientationApplied": true,
      "width": 1458
    },
    "path": "images/events/concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a_detail_v1.avif"
  },
  "events_concert_crowd_nh78jps73cwrt9mxyc017cjvm58ez76a_organizer": {
    "basename": "concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/events/concert-crowd-nh78jps73cwrt9mxyc017cjvm58ez76a_organizer_v1.avif"
  },
  "events_concert_crowd_nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_card": {
    "basename": "concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 675,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_card_v1.avif"
  },
  "events_concert_crowd_nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_detail": {
    "basename": "concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 820,
      "kind": "image",
      "orientationApplied": true,
      "width": 1458
    },
    "path": "images/events/concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_detail_v1.avif"
  },
  "events_concert_crowd_nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_organizer": {
    "basename": "concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/events/concert-crowd-nh7dvhqqmqn0cz2cs21vz4c6zn8eykgk_organizer_v1.avif"
  },
  "events_event_production_nh7476syzcrwz54edtj428968h8eym5f_card": {
    "basename": "event-production-nh7476syzcrwz54edtj428968h8eym5f",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 675,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/event-production-nh7476syzcrwz54edtj428968h8eym5f_card_v1.avif"
  },
  "events_event_production_nh7476syzcrwz54edtj428968h8eym5f_detail": {
    "basename": "event-production-nh7476syzcrwz54edtj428968h8eym5f",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 820,
      "kind": "image",
      "orientationApplied": true,
      "width": 1458
    },
    "path": "images/events/event-production-nh7476syzcrwz54edtj428968h8eym5f_detail_v1.avif"
  },
  "events_event_production_nh7476syzcrwz54edtj428968h8eym5f_organizer": {
    "basename": "event-production-nh7476syzcrwz54edtj428968h8eym5f",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/events/event-production-nh7476syzcrwz54edtj428968h8eym5f_organizer_v1.avif"
  },
  "events_festival_lights_nh7ecvyf3adc97vmxnx6jsq4218ey4ht_card": {
    "basename": "festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 675,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht_card_v1.avif"
  },
  "events_festival_lights_nh7ecvyf3adc97vmxnx6jsq4218ey4ht_detail": {
    "basename": "festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 820,
      "kind": "image",
      "orientationApplied": true,
      "width": 1458
    },
    "path": "images/events/festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht_detail_v1.avif"
  },
  "events_festival_lights_nh7ecvyf3adc97vmxnx6jsq4218ey4ht_organizer": {
    "basename": "festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/events/festival-lights-nh7ecvyf3adc97vmxnx6jsq4218ey4ht_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh72tbfd1jftgewc5ncymv4at58ezmea_card": {
    "basename": "fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea_card_v1.avif"
  },
  "events_fusion_header_grid_nh72tbfd1jftgewc5ncymv4at58ezmea_detail": {
    "basename": "fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea_detail_v1.avif"
  },
  "events_fusion_header_grid_nh72tbfd1jftgewc5ncymv4at58ezmea_organizer": {
    "basename": "fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh72tbfd1jftgewc5ncymv4at58ezmea_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh78pnhpsek20m3zdwvbn0vavd8eznx7_card": {
    "basename": "fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7_card_v1.avif"
  },
  "events_fusion_header_grid_nh78pnhpsek20m3zdwvbn0vavd8eznx7_detail": {
    "basename": "fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7_detail_v1.avif"
  },
  "events_fusion_header_grid_nh78pnhpsek20m3zdwvbn0vavd8eznx7_organizer": {
    "basename": "fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh78pnhpsek20m3zdwvbn0vavd8eznx7_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh78vheyqyjgng7212gtthf7as8eymaf_card": {
    "basename": "fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf_card_v1.avif"
  },
  "events_fusion_header_grid_nh78vheyqyjgng7212gtthf7as8eymaf_detail": {
    "basename": "fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf_detail_v1.avif"
  },
  "events_fusion_header_grid_nh78vheyqyjgng7212gtthf7as8eymaf_organizer": {
    "basename": "fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh78vheyqyjgng7212gtthf7as8eymaf_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_card": {
    "basename": "fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_card_v1.avif"
  },
  "events_fusion_header_grid_nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_detail": {
    "basename": "fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_detail_v1.avif"
  },
  "events_fusion_header_grid_nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_organizer": {
    "basename": "fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh79f2xge9m6qdmgdwfhhz6ymd8ezed7_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh7apb9qjnn89w19twzbgs9dz98eyfc5_card": {
    "basename": "fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5_card_v1.avif"
  },
  "events_fusion_header_grid_nh7apb9qjnn89w19twzbgs9dz98eyfc5_detail": {
    "basename": "fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5_detail_v1.avif"
  },
  "events_fusion_header_grid_nh7apb9qjnn89w19twzbgs9dz98eyfc5_organizer": {
    "basename": "fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7apb9qjnn89w19twzbgs9dz98eyfc5_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh7bv2swpmq5s4vr8x5bv958d58ey2gg_card": {
    "basename": "fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg_card_v1.avif"
  },
  "events_fusion_header_grid_nh7bv2swpmq5s4vr8x5bv958d58ey2gg_detail": {
    "basename": "fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg_detail_v1.avif"
  },
  "events_fusion_header_grid_nh7bv2swpmq5s4vr8x5bv958d58ey2gg_organizer": {
    "basename": "fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7bv2swpmq5s4vr8x5bv958d58ey2gg_organizer_v1.avif"
  },
  "events_fusion_header_grid_nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_card": {
    "basename": "fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "card",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 541,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/events/fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_card_v1.avif"
  },
  "events_fusion_header_grid_nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_detail": {
    "basename": "fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "detail",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_detail_v1.avif"
  },
  "events_fusion_header_grid_nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_organizer": {
    "basename": "fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr",
    "class": "image",
    "folders": [
      "events"
    ],
    "key": "organizer",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 577,
      "kind": "image",
      "orientationApplied": true,
      "width": 1280
    },
    "path": "images/events/fusion-header-grid-nh7e3tm8ca11qvw8s4rbywdr9x8eyckr_organizer_v1.avif"
  },
  "i1200x630_webp_eventoren_og": {
    "basename": "eventoren-og",
    "class": "image",
    "folders": [
      "1200x630_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": true,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 630,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/1200x630_webp/eventoren-og_default_v1.avif"
  },
  "i1920x1080_webp_concert_crowd": {
    "basename": "concert-crowd",
    "class": "image",
    "folders": [
      "1920x1080_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/1920x1080_webp/concert-crowd_default_v1.avif"
  },
  "i1920x1080_webp_dj_stage": {
    "basename": "dj-stage",
    "class": "image",
    "folders": [
      "1920x1080_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/1920x1080_webp/dj-stage_default_v1.avif"
  },
  "i1920x1080_webp_event_production": {
    "basename": "event-production",
    "class": "image",
    "folders": [
      "1920x1080_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/1920x1080_webp/event-production_default_v1.avif"
  },
  "i1920x1080_webp_festival_lights": {
    "basename": "festival-lights",
    "class": "image",
    "folders": [
      "1920x1080_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/1920x1080_webp/festival-lights_default_v1.avif"
  },
  "i1920x1080_webp_stage_beams": {
    "basename": "stage-beams",
    "class": "image",
    "folders": [
      "1920x1080_webp"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 1080,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/1920x1080_webp/stage-beams_default_v1.avif"
  },
  "i800x800_png_eventoren_checkout_branding": {
    "basename": "eventoren-checkout-branding",
    "class": "image",
    "folders": [
      "800x800_png"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": "Eventoren Checkout branding with the word EVENTOREN set vertically in bold navy capitals on a pale blue background.",
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 800,
      "kind": "image",
      "orientationApplied": true,
      "width": 800
    },
    "path": "images/800x800_png/eventoren-checkout-branding_default_v1.avif"
  },
  "i800x800_png_eventoren_checkout_branding_800x800_png": {
    "basename": "eventoren-checkout-branding",
    "class": "image",
    "folders": [
      "800x800_png"
    ],
    "key": "800x800_png",
    "mediaType": "image/png",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": "Eventoren Checkout branding with the word EVENTOREN set vertically in bold navy capitals on a pale blue background.",
      "animated": false,
      "colorSpace": "srgb",
      "format": "png",
      "frameCount": 1,
      "height": 800,
      "kind": "image",
      "orientationApplied": true,
      "width": 800
    },
    "path": "images/800x800_png/eventoren-checkout-branding_800x800_png_v1.png"
  },
  "pilates_card": {
    "basename": "card",
    "class": "image",
    "folders": [
      "pilates"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": "Pilates Christmas Event von Jennifer Kalus Hair Boutique und Flora Bonn mit Weihnachtsbaum",
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 900,
      "kind": "image",
      "orientationApplied": true,
      "width": 1200
    },
    "path": "images/pilates/card_default_v1.avif"
  },
  "pilates_detail": {
    "basename": "detail",
    "class": "image",
    "folders": [
      "pilates"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": "Pilates Christmas Event von Jennifer Kalus Hair Boutique und Flora Bonn mit Weihnachtsbaum",
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 820,
      "kind": "image",
      "orientationApplied": true,
      "width": 1920
    },
    "path": "images/pilates/detail_default_v1.avif"
  },
  "pilates_pilates_christmas_event": {
    "basename": "pilates-christmas-event",
    "class": "image",
    "folders": [
      "pilates"
    ],
    "key": "default",
    "mediaType": "image/avif",
    "metadata": {
      "aiProvenance": null,
      "alpha": false,
      "alt": null,
      "animated": false,
      "colorSpace": "srgb",
      "format": "avif",
      "frameCount": 1,
      "height": 723,
      "kind": "image",
      "orientationApplied": true,
      "width": 1234
    },
    "path": "images/pilates/pilates-christmas-event_default_v1.avif"
  }
} as const satisfies Record<string, CatalogImage>
