import type { ImageType } from "@adaptive-ds/assets-optimizer"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const imageList = {
  eventoren_og: {
    path: "eventoren-og_9669cb2c.webp",
    width: 1200,
    height: 630,
    alt: "Eventoren Veranstaltungen und Erlebnisse",
    mimeType: "image/webp",
  },
} as const satisfies Record<string, ImageType>
