import type { ImageType } from "@adaptive-ds/assets-optimizer"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const imageList = {
  concert_crowd: {
    path: "concert-crowd_460af152.webp",
    width: 1920,
    height: 1080,
    alt: "Ausverkauftes Konzert mit jubelnder Menge vor der Bühne",
    mimeType: "image/webp",
  },
  dj_stage: {
    path: "dj-stage_ba046940.webp",
    width: 1920,
    height: 1080,
    alt: "DJ am Pult auf einer Festivalbühne mit blauen Lichtstrahlen",
    mimeType: "image/webp",
  },
  event_production: {
    path: "event-production_193062e0.webp",
    width: 1920,
    height: 1080,
    alt: "Bühnenlichter, Scheinwerfer und Konzerthalle im atmosphärischen Nebel",
    mimeType: "image/webp",
  },
  eventoren_og: {
    path: "eventoren-og_9669cb2c.webp",
    width: 1200,
    height: 630,
    alt: "Eventoren Veranstaltungen und Erlebnisse",
    mimeType: "image/webp",
  },
  festival_lights: {
    path: "festival-lights_3f89b9a5.webp",
    width: 1920,
    height: 1080,
    alt: "Festivalbühne bei Nacht mit beleuchteter Kuppel und Publikum im Gegenlicht",
    mimeType: "image/webp",
  },
  stage_beams: {
    path: "stage-beams_0d113a31.webp",
    width: 1920,
    height: 1080,
    alt: "Lichtstrahlen und Nebel über der Live-Crowd vor der Hauptbühne",
    mimeType: "image/webp",
  },
} as const satisfies Record<string, ImageType>
