import type { VideoType } from "@adaptive-ds/assets-optimizer"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const videoList = {} as const satisfies Record<string, VideoType>
