import type { CatalogVideo } from "@adaptive-ds/assets-service"

// Auto-generated by @adaptive-ds/assets-service. Do not edit.
// schema: assets.catalog.v1
// catalog-digest: 99e855c9ce8268a898a0c9006906b6f0b7fa45478e0c4b625abe0912cdb08675
// renderer-version: 1
export const videoList = {} as const satisfies Record<string, CatalogVideo>
