import type { CatalogFont } from "@adaptive-ds/assets-service"

// Auto-generated by @adaptive-ds/assets-service. Do not edit.
// schema: assets.catalog.v1
// catalog-digest: f42ffaf7e0df2f8553afe695bee5d4521e4ec136a09f309eee0b9b924d02d1be
// renderer-version: 1
export const fontList = {} as const satisfies Record<string, CatalogFont>
