import type { DemoScenario } from "./demoScenarioSchema.js"

export const demoScenarios: [DemoScenario, ...DemoScenario[]] = [
  {
    id: "directory",
    path: "/demo",
    title: "Demo directory",
    detail: "Browse the local application fixture",
  },
  {
    id: "events",
    path: "/demo/events",
    title: "Event catalog",
    detail: "Search a local catalog and open an event detail workflow",
  },
  {
    id: "events-empty",
    path: "/demo/events-empty",
    title: "Empty event catalog",
    detail: "Review the production catalog empty state",
  },
  {
    id: "events-error",
    path: "/demo/events-error",
    title: "Event catalog error",
    detail: "Review the production catalog error state",
  },
  {
    id: "events-booking-success",
    path: "/demo/events-booking-success",
    title: "Booking success banner",
    detail: "Review and dismiss the production booking success state",
  },
  {
    id: "event-detail",
    path: "/demo/events/kraftklub-arena-berlin",
    title: "Event detail & tickets",
    detail: "Choose ticket tiers and add a local event to the cart",
  },
  {
    id: "event-detail-missing",
    path: "/demo/events/missing",
    title: "Missing event detail",
    detail: "Review the production missing-event state",
  },
  {
    id: "cart",
    path: "/demo/cart",
    title: "Cart",
    detail: "Review ticket groups, adjust quantities and continue to checkout",
  },
  {
    id: "cart-empty",
    path: "/demo/cart-empty",
    title: "Empty cart",
    detail: "Review the production empty-cart state",
  },
  {
    id: "checkout",
    path: "/demo/checkout",
    title: "Checkout",
    detail: "Complete a local guest checkout and view the wallet-ticket result",
  },
  {
    id: "checkout-empty",
    path: "/demo/checkout-empty",
    title: "Empty checkout",
    detail: "Review checkout without valid tickets",
  },
  {
    id: "checkout-error",
    path: "/demo/checkout-error",
    title: "Checkout error",
    detail: "Review a local checkout action failure",
  },
  {
    id: "order-status-paid",
    path: "/demo/order-status",
    title: "Order confirmation",
    detail: "Review a paid order status and wallet ticket",
  },
  {
    id: "order-status-pending",
    path: "/demo/order-status-pending",
    title: "Pending order status",
    detail: "Review a pending payment and unavailable pass",
  },
  {
    id: "order-status-error",
    path: "/demo/order-status-error",
    title: "Order status error",
    detail: "Review the production order lookup error state",
  },
  {
    id: "admin",
    path: "/demo/admin",
    title: "Catalog administration",
    detail: "Edit an event, update ticket products and publish local changes",
  },
  {
    id: "admin-new",
    path: "/demo/admin-new",
    title: "New event editor",
    detail: "Open the production editor with a new local event draft",
  },
  {
    id: "admin-empty",
    path: "/demo/admin-empty",
    title: "Empty member management",
    detail: "Review admin member management with no matching members",
  },
  {
    id: "admin-error",
    path: "/demo/admin-error",
    title: "Member management error",
    detail: "Review the production member loading error state",
  },
  {
    id: "admin-unauthorized",
    path: "/demo/admin-unauthorized",
    title: "Unauthorized admin",
    detail: "Review the production admin access fallback",
  },
  {
    id: "contact",
    path: "/demo/contact",
    title: "Contact & FAQ",
    detail: "Complete the local contact form and expand production FAQs",
  },
  {
    id: "contact-submitted",
    path: "/demo/contact-submitted",
    title: "Submitted contact",
    detail: "Review the production contact confirmation state",
  },
  {
    id: "navigation-menu",
    path: "/demo/navigation",
    title: "Mobile navigation drawer",
    detail: "Review the production mobile navigation modal with demo destinations",
  },
  {
    id: "auth-sign-in",
    path: "/demo/auth/sign-in",
    title: "Sign-in",
    detail: "Use the local password, email-code or SSO sign-in entry points",
  },
  {
    id: "auth-sign-in-error",
    path: "/demo/auth/sign-in-error",
    title: "Sign-in error",
    detail: "Review the production sign-in error state",
  },
  {
    id: "auth-otp",
    path: "/demo/auth/otp",
    title: "One-time code",
    detail: "Enter a local email sign-in code",
  },
  {
    id: "auth-otp-error",
    path: "/demo/auth/otp-error",
    title: "One-time code error",
    detail: "Review the production OTP error state",
  },
  {
    id: "orders-populated",
    path: "/demo/orders",
    title: "Order history",
    detail: "Browse local order history and open ticket details",
  },
  {
    id: "orders-empty",
    path: "/demo/orders-empty",
    title: "Empty order history",
    detail: "Review the production empty order history state",
  },
  {
    id: "orders-error",
    path: "/demo/orders-error",
    title: "Order history error",
    detail: "Review the production order history error and retry state",
  },
  {
    id: "orders-signed-out",
    path: "/demo/orders-signed-out",
    title: "Signed-out order history",
    detail: "Review the production sign-in prompt for order history",
  },
  {
    id: "organizer",
    path: "/demo/organizer",
    title: "Organizer events",
    detail: "Browse populated and empty local organizer event lists",
  },
  {
    id: "organizer-empty",
    path: "/demo/organizer-empty",
    title: "Empty organizer events",
    detail: "Review the production organizer empty-list state",
  },
  {
    id: "organizer-event",
    path: "/demo/organizer/event/xyz",
    title: "Organizer check-in",
    detail: "Search tickets and try manual, simulated QR and camera check-in states",
  },
  {
    id: "ratgeber",
    path: "/demo/ratgeber",
    title: "Ratgeber",
    detail: "Browse local guide articles and open a directly addressable article",
  },
  {
    id: "ratgeber-article",
    path: "/demo/ratgeber/events-sicher-planen",
    title: "Ratgeber article",
    detail: "Review the production article view with a local content fixture",
  },
  {
    id: "impressum",
    path: "/demo/impressum",
    title: "Impressum",
    detail: "Review the production legal view with local content",
  },
  {
    id: "datenschutz",
    path: "/demo/datenschutz",
    title: "Datenschutz",
    detail: "Review the German privacy page with local content",
  },
  {
    id: "privacy",
    path: "/demo/privacy",
    title: "Privacy",
    detail: "Review the English privacy page with local content",
  },
  {
    id: "agb",
    path: "/demo/agb",
    title: "AGB",
    detail: "Review the production AGB view with local content",
  },
  {
    id: "terms",
    path: "/demo/terms",
    title: "Terms",
    detail: "Review the English terms page with local content",
  },
  {
    id: "abiball-redirect",
    path: "/demo/abiball-2027",
    title: "Abiball 2027 redirect",
    detail: "Review the production redirect handoff to the static HTML page",
  },
]
