import type { DemoScenario } from "./demoScenarioSchema.js"

export const demoScenarios: [DemoScenario, ...DemoScenario[]] = [
  {
    id: "directory",
    path: "/demo",
    title: "Demo-Verzeichnis",
    detail: "Lokale Anwendungs-Fixtures durchsuchen",
  },
  {
    id: "events",
    path: "/demo/events",
    title: "Eventkatalog",
    detail: "Lokalen Katalog durchsuchen und Eventdetails öffnen",
  },
  {
    id: "events-empty",
    path: "/demo/events-empty",
    title: "Leerer Eventkatalog",
    detail: "Produktionszustand ohne passende Events anzeigen",
  },
  {
    id: "events-error",
    path: "/demo/events-error",
    title: "Eventkatalog-Fehler",
    detail: "Produktionszustand mit Katalogfehler anzeigen",
  },
  {
    id: "events-booking-success",
    path: "/demo/events-booking-success",
    title: "Buchungsbestätigung",
    detail: "Produktionsbanner anzeigen und schließen",
  },
  {
    id: "event-detail",
    path: "/demo/events/kraftklub-arena-berlin",
    title: "Eventdetails & Tickets",
    detail: "Ticketstufen auswählen und ein lokales Event in den Warenkorb legen",
  },
  {
    id: "event-detail-missing",
    path: "/demo/events/missing",
    title: "Fehlendes Event",
    detail: "Produktionszustand für ein nicht gefundenes Event anzeigen",
  },
  {
    id: "cart",
    path: "/demo/cart",
    title: "Warenkorb",
    detail: "Ticketgruppen prüfen, Mengen ändern und zur Kasse gehen",
  },
  {
    id: "cart-empty",
    path: "/demo/cart-empty",
    title: "Leerer Warenkorb",
    detail: "Produktionszustand mit leerem Warenkorb anzeigen",
  },
  {
    id: "checkout",
    path: "/demo/checkout",
    title: "Kasse",
    detail: "Lokalen Gast-Checkout abschließen und Wallet-Ticket anzeigen",
  },
  {
    id: "checkout-empty",
    path: "/demo/checkout-empty",
    title: "Leere Kasse",
    detail: "Checkout ohne gültige Tickets anzeigen",
  },
  {
    id: "checkout-error",
    path: "/demo/checkout-error",
    title: "Checkout-Fehler",
    detail: "Lokalen Fehler beim Abschließen der Kasse anzeigen",
  },
  {
    id: "order-status-paid",
    path: "/demo/order-status",
    title: "Bestellbestätigung",
    detail: "Bezahlten Status und Wallet-Ticket anzeigen",
  },
  {
    id: "order-status-pending",
    path: "/demo/order-status-pending",
    title: "Offener Zahlungsstatus",
    detail: "Ausstehende Zahlung und fehlendes Wallet-Ticket anzeigen",
  },
  {
    id: "order-status-error",
    path: "/demo/order-status-error",
    title: "Bestellstatus-Fehler",
    detail: "Fehler beim Laden des Produktionszustands anzeigen",
  },
  {
    id: "admin",
    path: "/demo/admin",
    title: "Katalogverwaltung",
    detail: "Event bearbeiten, Ticketprodukte aktualisieren und lokale Änderungen veröffentlichen",
  },
  {
    id: "admin-new",
    path: "/demo/admin-new",
    title: "Neuer Evententwurf",
    detail: "Produktionseditor mit lokalem neuen Entwurf öffnen",
  },
  {
    id: "admin-empty",
    path: "/demo/admin-empty",
    title: "Keine Mitglieder",
    detail: "Mitgliederverwaltung ohne Treffer anzeigen",
  },
  {
    id: "admin-error",
    path: "/demo/admin-error",
    title: "Mitgliederfehler",
    detail: "Fehlerzustand der Produktions-Mitgliederverwaltung anzeigen",
  },
  {
    id: "admin-unauthorized",
    path: "/demo/admin-unauthorized",
    title: "Admin-Zugriff verweigert",
    detail: "Produktions-Fallback für fehlende Berechtigung anzeigen",
  },
  {
    id: "contact",
    path: "/demo/contact",
    title: "Kontakt & FAQ",
    detail: "Lokales Kontaktformular und Produktions-FAQs ausprobieren",
  },
  {
    id: "contact-submitted",
    path: "/demo/contact-submitted",
    title: "Gesendeter Kontakt",
    detail: "Bestätigungszustand des Produktionsformulars anzeigen",
  },
  {
    id: "navigation-menu",
    path: "/demo/navigation",
    title: "Mobiles Navigationsmenü",
    detail: "Produktionsdialog mit Demo-Zielen anzeigen",
  },
  {
    id: "auth-sign-in",
    path: "/demo/auth/sign-in",
    title: "Anmeldung",
    detail: "Lokale Passwort-, E-Mail-Code- und SSO-Einstiege anzeigen",
  },
  {
    id: "auth-sign-in-error",
    path: "/demo/auth/sign-in-error",
    title: "Anmeldefehler",
    detail: "Fehlerzustand der Produktionsanmeldung anzeigen",
  },
  {
    id: "auth-otp",
    path: "/demo/auth/otp",
    title: "Einmalcode",
    detail: "Lokalen E-Mail-Anmeldecode eingeben",
  },
  {
    id: "auth-otp-error",
    path: "/demo/auth/otp-error",
    title: "Einmalcode-Fehler",
    detail: "Fehlerzustand der Produktions-OTP-Eingabe anzeigen",
  },
  {
    id: "orders-populated",
    path: "/demo/orders",
    title: "Bestellhistorie",
    detail: "Lokale Bestellungen durchsuchen und Ticketdetails öffnen",
  },
  {
    id: "orders-empty",
    path: "/demo/orders-empty",
    title: "Leere Bestellhistorie",
    detail: "Leeren Produktionszustand anzeigen",
  },
  {
    id: "orders-error",
    path: "/demo/orders-error",
    title: "Bestellhistorienfehler",
    detail: "Fehler- und Wiederholungszustand anzeigen",
  },
  {
    id: "orders-signed-out",
    path: "/demo/orders-signed-out",
    title: "Abgemeldete Bestellungen",
    detail: "Anmeldehinweis der Produktionshistorie anzeigen",
  },
  {
    id: "organizer",
    path: "/demo/organizer",
    title: "Veranstalter-Events",
    detail: "Befüllte und leere lokale Veranstalter-Eventlisten anzeigen",
  },
  {
    id: "organizer-empty",
    path: "/demo/organizer-empty",
    title: "Leere Veranstalter-Events",
    detail: "Leere Produktionsliste des Veranstalterbereichs anzeigen",
  },
  {
    id: "organizer-event",
    path: "/demo/organizer/event/xyz",
    title: "Veranstalter-Check-in",
    detail: "Tickets suchen und manuelle, simulierte QR- sowie Kamera-Check-ins ausprobieren",
  },
  {
    id: "ratgeber",
    path: "/demo/ratgeber",
    title: "Ratgeber",
    detail: "Lokale Ratgeberartikel durchsuchen und einen direkt aufrufbaren Artikel öffnen",
  },
  {
    id: "ratgeber-article",
    path: "/demo/ratgeber/events-sicher-planen",
    title: "Ratgeberartikel",
    detail: "Produktionsansicht mit lokalen Inhaltsdaten anzeigen",
  },
  {
    id: "impressum",
    path: "/demo/impressum",
    title: "Impressum",
    detail: "Produktionsansicht mit lokalen Rechtsinhalten anzeigen",
  },
  {
    id: "datenschutz",
    path: "/demo/datenschutz",
    title: "Datenschutz",
    detail: "Deutsche Datenschutzseite mit lokalen Inhalten anzeigen",
  },
  {
    id: "privacy",
    path: "/demo/privacy",
    title: "Datenschutz",
    detail: "Datenschutzseite mit lokalen Inhalten anzeigen",
  },
  {
    id: "agb",
    path: "/demo/agb",
    title: "AGB",
    detail: "Produktionsansicht der AGB mit lokalen Inhalten anzeigen",
  },
  {
    id: "terms",
    path: "/demo/terms",
    title: "AGB",
    detail: "AGB-Seite mit lokalen Inhalten anzeigen",
  },
  {
    id: "abiball-redirect",
    path: "/demo/abiball-2027",
    title: "Weiterleitung Abiball 2027",
    detail: "Produktionsweiterleitung zur statischen HTML-Seite anzeigen",
  },
]
