import type { EventItem } from "./EventItem.ts"

export const eventListMock: readonly EventItem[] = [
  {
    id: "reise-toskana-weinwoche",
    title: "Toskana Weinwoche",
    subtitle: "6 Tage Chianti, Kochkurs und Weingutbesuche",
    description:
      "Agriturismo bei Greve in Chianti, drei Verkostungen auf familiengeführten Weingütern, ein Kochkurs mit lokaler Küche und ein Tagesausflug nach Siena.",
    category: "reisen",
    startsAt: "2026-05-16T10:00:00+02:00",
    endsAt: "2026-05-22T16:00:00+02:00",
    doorsAt: "2026-05-16T08:00:00+02:00",
    venue: "Agriturismo Le Vigne",
    city: "Greve in Chianti",
    address: "Via San Cresci 12, 50022 Greve in Chianti, Italien",
    organizer: "Eventoren Reisen",
    imageUrl: "/images/festival-lights_3f89b9a5.webp",
    imageAlt: "Weinberge in hügeliger Landschaft",
    tags: ["Reise", "Kulinarik", "Kleingruppe"],
    soldOut: false,
    tiers: [
      {
        id: "standard",
        name: "Standardzimmer pro Person",
        description: "Sechs Nächte, Halbpension und alle Verkostungen.",
        priceCents: 98000,
        feeCents: 3900,
        available: 9,
      },
    ],
  },
  {
    id: "fusion-festival",
    title: "Fusion Festival – Ferienkommunismus",
    subtitle: "Vier Tage Musik, Theater und Performance am Flugplatz Lärz",
    description:
      "Elektronische Musik, Zirkus und Theater auf dem ehemaligen Militärflugplatz. Tickets werden im Losverfahren vergeben, Restkontingente kommen tagesaktuell in den Verkauf.",
    category: "festivals",
    startsAt: "2026-06-24T14:00:00+02:00",
    endsAt: "2026-06-28T12:00:00+02:00",
    doorsAt: "2026-06-24T10:00:00+02:00",
    venue: "Flugplatz Lärz",
    city: "Lärz",
    address: "Zum Flugplatz 1, 17248 Lärz",
    organizer: "Kulturkosmos Müritz e.V.",
    imageUrl: "/images/dj-stage_ba046940.webp",
    imageAlt: "Menschenmenge auf einem Festivalgelände",
    tags: ["Elektro", "Performance", "Losverfahren"],
    soldOut: false,
    tiers: [
      {
        id: "vollticket",
        name: "Vollticket",
        description: "Zutritt für alle vier Tage inklusive Camping.",
        priceCents: 22000,
        feeCents: 990,
        available: 45,
      },
      {
        id: "soli",
        name: "Soli-Ticket",
        description: "Ermöglicht ermäßigte Tickets für andere Besucher:innen.",
        priceCents: 28000,
        feeCents: 990,
        available: 60,
      },
    ],
  },
  {
    id: "splash-hiphop-festival",
    title: "splash! Festival",
    subtitle: "Hip-Hop und Rap am Ferropolis",
    description:
      "Drei Tage Rap auf der Halbinsel Ferropolis zwischen historischen Baggern. Camping, Badestrand und Skatepark sind im Festivalticket enthalten.",
    category: "festivals",
    startsAt: "2026-07-03T12:00:00+02:00",
    endsAt: "2026-07-05T23:59:00+02:00",
    doorsAt: "2026-07-02T10:00:00+02:00",
    venue: "Ferropolis",
    city: "Gräfenhainichen",
    address: "Ferropolisstraße 1, 06773 Gräfenhainichen",
    organizer: "Superstruct Entertainment",
    imageUrl: "/images/festival-lights_3f89b9a5.webp",
    imageAlt: "Festivalbühne vor Industriekulisse",
    tags: ["Hip-Hop", "Camping", "3 Tage"],
    soldOut: false,
    tiers: [
      {
        id: "festival",
        name: "Festivalticket",
        description: "Alle drei Tage inklusive Campingplatz.",
        priceCents: 19900,
        feeCents: 1200,
        available: 210,
      },
      {
        id: "comfort",
        name: "Comfort Camping",
        description: "Festivalticket plus vorgebautes Zelt und Duschzugang.",
        priceCents: 31900,
        feeCents: 1600,
        available: 22,
      },
    ],
  },
]
