import type { EventItem } from "./EventItem.ts"
import { eventImagePlaceholder } from "./eventImagePlaceholder.ts"

export const eventListMock: readonly EventItem[] = [
  {
    id: "kraftklub-arena-berlin",
    title: "Kraftklub — Karges Land Tour",
    subtitle: "Indie-Rock aus Chemnitz, live in der Uber Arena",
    description:
      "Kraftklub bringen ihre ausverkaufte Hallentour nach Berlin: laute Gitarren, Konfettikanonen und Singalongs von 'Karl-Marx-Stadt' bis zu den neuen Songs. Support kommt von Blond.",
    category: "konzerte",
    startsAt: "2026-09-12T20:00:00+02:00",
    endsAt: "2026-09-12T23:00:00+02:00",
    doorsAt: "2026-09-12T18:30:00+02:00",
    venue: "Uber Arena",
    city: "Berlin",
    address: "Mühlenstraße 12–30, 10243 Berlin",
    organizer: "Trinity Music GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Bühnenbild eines Rockkonzerts",
    tags: ["Indie", "Rock", "Support: Blond"],
    soldOut: false,
    tiers: [
      {
        id: "innenraum",
        name: "Innenraum Stehplatz",
        description: "Freie Platzwahl im Innenraum, direkt vor der Bühne.",
        priceCents: 5490,
        feeCents: 549,
        available: 240,
      },
      {
        id: "oberrang",
        name: "Oberrang Sitzplatz",
        description: "Nummerierter Sitzplatz mit voller Bühnensicht.",
        priceCents: 6990,
        feeCents: 699,
        available: 86,
      },
      {
        id: "earlyentry",
        name: "Early Entry Paket",
        description: "Einlass 60 Minuten vor Türöffnung inkl. Tourposter.",
        priceCents: 8900,
        feeCents: 890,
        available: 24,
      },
    ],
  },
  {
    id: "philharmonie-mahler-5",
    title: "Mahler 5 — Elbphilharmonie",
    subtitle: "NDR Elbphilharmonie Orchester, Dirigat: Alan Gilbert",
    description:
      "Gustav Mahlers 5. Sinfonie im Großen Saal der Elbphilharmonie. Vor der Pause erklingt das Adagietto in einer Kammerfassung, eingeführt durch ein 30-minütiges Konzertgespräch.",
    category: "kultur",
    startsAt: "2026-10-03T19:30:00+02:00",
    endsAt: "2026-10-03T21:45:00+02:00",
    doorsAt: "2026-10-03T18:45:00+02:00",
    venue: "Elbphilharmonie, Großer Saal",
    city: "Hamburg",
    address: "Platz der Deutschen Einheit 4, 20457 Hamburg",
    organizer: "Elbphilharmonie Hamburg",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Konzertsaal mit Orchester",
    tags: ["Klassik", "Sinfonie", "Konzerteinführung"],
    soldOut: false,
    tiers: [
      {
        id: "kategorie-a",
        name: "Kategorie A",
        description: "Beste Sicht und Akustik im Parkett Mitte.",
        priceCents: 11500,
        feeCents: 690,
        available: 32,
      },
      {
        id: "kategorie-c",
        name: "Kategorie C",
        description: "Seitliche Ränge, volle Akustik.",
        priceCents: 6500,
        feeCents: 390,
        available: 118,
      },
    ],
  },
  {
    id: "wacken-open-air",
    title: "Wacken Open Air 2026",
    subtitle: "Drei Tage Metal auf dem Holy Ground",
    description:
      "Über 70 Bands auf sechs Bühnen, Campingplatz ab Mittwoch geöffnet, inklusive Shuttle vom Bahnhof Itzehoe. Das Festivalticket gilt für alle Tage und den Zeltplatz.",
    category: "festivals",
    startsAt: "2026-07-30T12:00:00+02:00",
    endsAt: "2026-08-01T23:59:00+02:00",
    doorsAt: "2026-07-29T10:00:00+02:00",
    venue: "Festivalgelände Wacken",
    city: "Wacken",
    address: "Am Weidenkamp, 25596 Wacken",
    organizer: "ICS Festival Service GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Festivalgelände bei Sonnenuntergang",
    tags: ["Metal", "Camping", "3 Tage"],
    soldOut: true,
    tiers: [
      {
        id: "festival-ticket",
        name: "Festivalticket inkl. Camping",
        description: "Zutritt zu allen drei Festivaltagen und zum Zeltplatz.",
        priceCents: 33300,
        feeCents: 1500,
        available: 0,
      },
    ],
  },
  {
    id: "fusion-festival",
    title: "Fusion Festival — Ferienkommunismus",
    subtitle: "Vier Tage Musik, Theater und Performance am Flugplatz Lärz",
    description:
      "Elektronische Musik, Zirkus und Theater auf dem ehemaligen Militärflugplatz. Tickets werden im Losverfahren vergeben, Restkontingente kommen tagesaktuell in den Verkauf.",
    category: "festivals",
    startsAt: "2026-06-24T14:00:00+02:00",
    endsAt: "2026-06-28T12:00:00+02:00",
    doorsAt: "2026-06-24T10:00:00+02:00",
    venue: "Flugplatz Lärz",
    city: "Lärz",
    address: "Zum Flugplatz 1, 17248 Lärz",
    organizer: "Kulturkosmos Müritz e.V.",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Menschenmenge auf einem Festivalgelände",
    tags: ["Elektro", "Performance", "Losverfahren"],
    soldOut: false,
    tiers: [
      {
        id: "vollticket",
        name: "Vollticket",
        description: "Zutritt für alle vier Tage inklusive Camping.",
        priceCents: 22000,
        feeCents: 990,
        available: 45,
      },
      {
        id: "soli",
        name: "Soli-Ticket",
        description: "Ermöglicht ermäßigte Tickets für andere Besucher:innen.",
        priceCents: 28000,
        feeCents: 990,
        available: 60,
      },
    ],
  },
  {
    id: "schauspielhaus-faust",
    title: "Faust I — Schauspielhaus Bochum",
    subtitle: "Regie: Johan Simons, mit Publikumsgespräch",
    description:
      "Goethes Klassiker in einer kargen, konzentrierten Inszenierung. Nach der Vorstellung lädt das Ensemble zum moderierten Publikumsgespräch im Foyer.",
    category: "kultur",
    startsAt: "2026-09-19T19:00:00+02:00",
    endsAt: "2026-09-19T22:00:00+02:00",
    doorsAt: "2026-09-19T18:15:00+02:00",
    venue: "Schauspielhaus Bochum",
    city: "Bochum",
    address: "Königsallee 15, 44789 Bochum",
    organizer: "Schauspielhaus Bochum",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Theaterbühne mit Scheinwerferlicht",
    tags: ["Theater", "Klassiker", "Publikumsgespräch"],
    soldOut: false,
    tiers: [
      {
        id: "parkett",
        name: "Parkett",
        description: "Reihen 3–12, mittige Sicht auf die Bühne.",
        priceCents: 4200,
        feeCents: 250,
        available: 74,
      },
      {
        id: "ermaessigt",
        name: "Ermäßigt",
        description: "Für Schüler:innen, Studierende und Azubis, Nachweis am Einlass.",
        priceCents: 1500,
        feeCents: 150,
        available: 40,
      },
    ],
  },
  {
    id: "bundesliga-bvb-sge",
    title: "Borussia Dortmund — Eintracht Frankfurt",
    subtitle: "Bundesliga, 7. Spieltag im Signal Iduna Park",
    description:
      "81.365 Plätze, Südtribüne inklusive. Das Ticket gilt drei Stunden vor und nach dem Anpfiff als Fahrkarte im VRR-Gebiet.",
    category: "sport",
    startsAt: "2026-10-17T15:30:00+02:00",
    endsAt: "2026-10-17T17:20:00+02:00",
    doorsAt: "2026-10-17T13:30:00+02:00",
    venue: "Signal Iduna Park",
    city: "Dortmund",
    address: "Strobelallee 50, 44139 Dortmund",
    organizer: "Borussia Dortmund GmbH & Co. KGaA",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Volles Fußballstadion",
    tags: ["Fußball", "Bundesliga", "ÖPNV inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "suedtribuene",
        name: "Südtribüne Stehplatz",
        description: "Die Gelbe Wand, unnummerierter Stehplatz.",
        priceCents: 1800,
        feeCents: 200,
        available: 310,
      },
      {
        id: "haupttribuene",
        name: "Haupttribüne Sitzplatz",
        description: "Überdachter Sitzplatz auf Höhe der Mittellinie.",
        priceCents: 7500,
        feeCents: 450,
        available: 52,
      },
    ],
  },
  {
    id: "berlin-marathon-startplatz",
    title: "BMW Berlin-Marathon — Startplatz",
    subtitle: "42,195 km durch die Hauptstadt",
    description:
      "Startplatz inklusive Zeitmessung, Finisher-Shirt und Medaille. Startblockzuteilung erfolgt nach nachgewiesener Bestzeit, Startunterlagen gibt es auf der Marathon-Messe.",
    category: "sport",
    startsAt: "2026-09-27T09:15:00+02:00",
    endsAt: "2026-09-27T15:30:00+02:00",
    doorsAt: "2026-09-27T07:00:00+02:00",
    venue: "Straße des 17. Juni",
    city: "Berlin",
    address: "Straße des 17. Juni, 10557 Berlin",
    organizer: "SCC EVENTS GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Läuferfeld auf einer Straße",
    tags: ["Laufen", "Marathon", "Zeitmessung"],
    soldOut: false,
    tiers: [
      {
        id: "startplatz",
        name: "Startplatz Marathon",
        description: "Inklusive Zeitmessung, Verpflegung und Medaille.",
        priceCents: 15500,
        feeCents: 800,
        available: 130,
      },
      {
        id: "staffel",
        name: "Staffel (4 Läufer:innen)",
        description: "Teamstart mit Wechselzonen entlang der Strecke.",
        priceCents: 27000,
        feeCents: 1200,
        available: 18,
      },
    ],
  },
  {
    id: "reise-nordlichter-tromsoe",
    title: "Nordlichter-Reise Tromsø",
    subtitle: "5 Tage Polarlichtjagd inkl. Flug und Guide",
    description:
      "Flug ab Frankfurt, vier Nächte im Hotel im Zentrum von Tromsø, zwei geführte Nordlicht-Touren mit Thermoanzügen sowie eine Fjordfahrt mit Hybridkatamaran.",
    category: "reisen",
    startsAt: "2026-11-14T06:00:00+01:00",
    endsAt: "2026-11-19T21:00:00+01:00",
    doorsAt: "2026-11-14T04:00:00+01:00",
    venue: "Abflug Frankfurt am Main",
    city: "Tromsø",
    address: "Flughafen Frankfurt, Terminal 1, 60547 Frankfurt am Main",
    organizer: "Eventoren Reisen",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Nordlichter über verschneiter Landschaft",
    tags: ["Reise", "5 Tage", "Flug inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "doppelzimmer",
        name: "Doppelzimmer pro Person",
        description: "Vier Nächte im Doppelzimmer inklusive Frühstück.",
        priceCents: 129900,
        feeCents: 4900,
        available: 14,
      },
      {
        id: "einzelzimmer",
        name: "Einzelzimmer",
        description: "Vier Nächte im Einzelzimmer inklusive Frühstück.",
        priceCents: 154900,
        feeCents: 4900,
        available: 6,
      },
    ],
  },
  {
    id: "reise-toskana-weinwoche",
    title: "Toskana Weinwoche",
    subtitle: "6 Tage Chianti, Kochkurs und Weingutbesuche",
    description:
      "Agriturismo bei Greve in Chianti, drei Verkostungen auf familiengeführten Weingütern, ein Kochkurs mit lokaler Küche und ein Tagesausflug nach Siena.",
    category: "reisen",
    startsAt: "2026-05-16T10:00:00+02:00",
    endsAt: "2026-05-22T16:00:00+02:00",
    doorsAt: "2026-05-16T08:00:00+02:00",
    venue: "Agriturismo Le Vigne",
    city: "Greve in Chianti",
    address: "Via San Cresci 12, 50022 Greve in Chianti, Italien",
    organizer: "Eventoren Reisen",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Weinberge in hügeliger Landschaft",
    tags: ["Reise", "Kulinarik", "Kleingruppe"],
    soldOut: false,
    tiers: [
      {
        id: "standard",
        name: "Standardzimmer pro Person",
        description: "Sechs Nächte, Halbpension und alle Verkostungen.",
        priceCents: 98000,
        feeCents: 3900,
        available: 9,
      },
    ],
  },
  {
    id: "jazzclub-nightsession",
    title: "Late Night Session im Stadtgarten",
    subtitle: "Julia Hülsmann Quartett, zwei Sets",
    description:
      "Zwei Sets modernen europäischen Jazz mit anschließender offener Jam Session. Bestuhlung an Clubtischen, Getränke am Platz.",
    category: "konzerte",
    startsAt: "2026-08-29T21:00:00+02:00",
    endsAt: "2026-08-30T01:00:00+02:00",
    doorsAt: "2026-08-29T20:00:00+02:00",
    venue: "Stadtgarten Köln",
    city: "Köln",
    address: "Venloer Straße 40, 50672 Köln",
    organizer: "Stadtgarten Köln",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Jazzband in einem Club",
    tags: ["Jazz", "Late Night", "Jam Session"],
    soldOut: false,
    tiers: [
      {
        id: "clubtisch",
        name: "Clubtisch",
        description: "Sitzplatz an Zweiertischen mit Getränkeservice.",
        priceCents: 3200,
        feeCents: 280,
        available: 46,
      },
    ],
  },
  {
    id: "museumsnacht-muenchen",
    title: "Lange Nacht der Museen",
    subtitle: "90 Häuser, ein Ticket, Shuttlebusse inklusive",
    description:
      "Von 19 bis 2 Uhr öffnen 90 Museen und Sammlungen in München. Das Ticket gilt für alle Häuser und die Shuttlebuslinien zwischen den Standorten.",
    category: "kultur",
    startsAt: "2026-10-24T19:00:00+02:00",
    endsAt: "2026-10-25T02:00:00+02:00",
    doorsAt: "2026-10-24T18:30:00+02:00",
    venue: "Verschiedene Häuser",
    city: "München",
    address: "Startpunkt: Königsplatz, 80333 München",
    organizer: "München Ticket GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Beleuchtetes Museumsgebäude bei Nacht",
    tags: ["Museum", "Nachtveranstaltung", "Shuttle inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "kombiticket",
        name: "Kombiticket",
        description: "Eintritt in alle teilnehmenden Häuser plus Shuttle.",
        priceCents: 2000,
        feeCents: 180,
        available: 480,
      },
    ],
  },
  {
    id: "splash-hiphop-festival",
    title: "splash! Festival",
    subtitle: "Hip-Hop und Rap am Ferropolis",
    description:
      "Drei Tage Rap auf der Halbinsel Ferropolis zwischen historischen Baggern. Camping, Badestrand und Skatepark sind im Festivalticket enthalten.",
    category: "festivals",
    startsAt: "2026-07-03T12:00:00+02:00",
    endsAt: "2026-07-05T23:59:00+02:00",
    doorsAt: "2026-07-02T10:00:00+02:00",
    venue: "Ferropolis",
    city: "Gräfenhainichen",
    address: "Ferropolisstraße 1, 06773 Gräfenhainichen",
    organizer: "Superstruct Entertainment",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Festivalbühne vor Industriekulisse",
    tags: ["Hip-Hop", "Camping", "3 Tage"],
    soldOut: false,
    tiers: [
      {
        id: "festival",
        name: "Festivalticket",
        description: "Alle drei Tage inklusive Campingplatz.",
        priceCents: 19900,
        feeCents: 1200,
        available: 210,
      },
      {
        id: "comfort",
        name: "Comfort Camping",
        description: "Festivalticket plus vorgebautes Zelt und Duschzugang.",
        priceCents: 31900,
        feeCents: 1600,
        available: 22,
      },
    ],
  },
  {
    id: "open-air-kino-hafen",
    title: "Open-Air-Kino am Hafen",
    subtitle: "Perfect Days (OmU) unter freiem Himmel",
    description:
      "Wim Wenders' Tokio-Porträt auf der 12-Meter-Leinwand am Zollhafen. Liegestühle und Decken sind vorhanden, bei Regen wird auf den Folgetag verschoben.",
    category: "kultur",
    startsAt: "2026-08-28T21:15:00+02:00",
    endsAt: "2026-08-28T23:30:00+02:00",
    doorsAt: "2026-08-28T19:30:00+02:00",
    venue: "Zollhafen Nordmole",
    city: "Mainz",
    address: "Rheinallee 3, 55118 Mainz",
    organizer: "Kinoinitiative Mainz e.V.",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Freiluftkino mit großer Leinwand bei Dämmerung",
    tags: ["Film", "Open Air", "Originalfassung"],
    soldOut: false,
    tiers: [
      {
        id: "liegestuhl",
        name: "Liegestuhl",
        description: "Reservierter Liegestuhl in den vorderen Reihen.",
        priceCents: 1400,
        feeCents: 120,
        available: 58,
      },
      {
        id: "wiese",
        name: "Wiesenplatz",
        description: "Freie Platzwahl auf der Wiese, Decke mitbringen.",
        priceCents: 900,
        feeCents: 90,
        available: 140,
      },
    ],
  },
  {
    id: "technoclub-warehouse-nacht",
    title: "Warehouse Night — Amelie Lens",
    subtitle: "Techno bis in den Morgen, drei Floors",
    description:
      "Amelie Lens spielt ein erweitertes Closing-Set im Hauptfloor, dazu lokale Acts im Keller und ein Ambient-Floor im Hof. Einlass ab 18 Jahren, keine Handykameras.",
    category: "konzerte",
    startsAt: "2026-08-29T23:00:00+02:00",
    endsAt: "2026-08-30T10:00:00+02:00",
    doorsAt: "2026-08-29T22:30:00+02:00",
    venue: "Kraftwerk Mitte",
    city: "Berlin",
    address: "Köpenicker Straße 70, 10179 Berlin",
    organizer: "Nachtkultur Booking",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Dunkler Clubraum mit Lichtanlage",
    tags: ["Techno", "Ab 18", "Drei Floors"],
    soldOut: false,
    tiers: [
      {
        id: "presale",
        name: "Vorverkauf",
        description: "Einlass ab 23 Uhr, Vorverkaufskontingent.",
        priceCents: 2500,
        feeCents: 300,
        available: 190,
      },
      {
        id: "fastlane",
        name: "Fast Lane",
        description: "Bevorzugter Einlass ohne Wartezeit an der Schlange.",
        priceCents: 3800,
        feeCents: 380,
        available: 35,
      },
    ],
  },
  {
    id: "streetfood-markt-sonntag",
    title: "Street Food Sonntag am Rheinufer",
    subtitle: "40 Stände, Livemusik und Familienprogramm",
    description:
      "Von koreanischen Bao bis zur schwäbischen Maultasche: 40 Stände am Rheinufer, dazu Livebands ab 14 Uhr und ein Bastelzelt für Kinder. Eintritt gilt für den ganzen Tag.",
    category: "kultur",
    startsAt: "2026-08-30T11:00:00+02:00",
    endsAt: "2026-08-30T20:00:00+02:00",
    doorsAt: "2026-08-30T10:30:00+02:00",
    venue: "Rheinwiesen Oberkassel",
    city: "Düsseldorf",
    address: "Rheinwiesen, 40545 Düsseldorf",
    organizer: "Rheinmarkt Veranstaltungs GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Marktstände mit Essen an einem Flussufer",
    tags: ["Kulinarik", "Familie", "Livemusik"],
    soldOut: false,
    tiers: [
      {
        id: "tagesticket",
        name: "Tagesticket",
        description: "Eintritt für eine Person, ganztägig gültig.",
        priceCents: 600,
        feeCents: 90,
        available: 900,
      },
      {
        id: "familie",
        name: "Familienticket",
        description: "Zwei Erwachsene und bis zu drei Kinder unter 14.",
        priceCents: 1500,
        feeCents: 150,
        available: 210,
      },
    ],
  },
  {
    id: "handball-thw-kiel-rn-loewen",
    title: "THW Kiel — Rhein-Neckar Löwen",
    subtitle: "Handball-Bundesliga im Wunderino Nord",
    description:
      "Spitzenspiel in einer der lautesten Handballhallen Europas. Hallenöffnung 90 Minuten vor Anwurf, Bezahlung im Innenraum nur bargeldlos.",
    category: "sport",
    startsAt: "2026-09-05T18:00:00+02:00",
    endsAt: "2026-09-05T19:50:00+02:00",
    doorsAt: "2026-09-05T16:30:00+02:00",
    venue: "Wunderino Arena",
    city: "Kiel",
    address: "Europaplatz 1, 24103 Kiel",
    organizer: "THW Kiel Handball-Bundesliga GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Handballhalle mit Zuschauerrängen",
    tags: ["Handball", "Bundesliga", "Bargeldlos"],
    soldOut: false,
    tiers: [
      {
        id: "steh-nord",
        name: "Stehplatz Nordkurve",
        description: "Unnummerierter Stehplatz im Fanblock.",
        priceCents: 2200,
        feeCents: 200,
        available: 260,
      },
      {
        id: "sitz-mitte",
        name: "Sitzplatz Mittelblock",
        description: "Nummerierter Sitzplatz auf Höhe der Mittellinie.",
        priceCents: 5900,
        feeCents: 400,
        available: 64,
      },
    ],
  },
  {
    id: "oktoberfest-zeltreservierung",
    title: "Oktoberfest — Tischreservierung Schottenhamel",
    subtitle: "Abendbox für zehn Personen inkl. Verzehrmarken",
    description:
      "Reservierter Tisch im Festzelt Schottenhamel für den Abendbetrieb. Enthalten sind zehn Maß Bier und zehn Hendl, weitere Bestellungen laufen über die Bedienung.",
    category: "festivals",
    startsAt: "2026-09-26T17:00:00+02:00",
    endsAt: "2026-09-26T23:00:00+02:00",
    doorsAt: "2026-09-26T16:30:00+02:00",
    venue: "Festzelt Schottenhamel",
    city: "München",
    address: "Theresienwiese, 80336 München",
    organizer: "Schottenhamel Festhalle",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Volles Bierzelt mit langen Tischreihen",
    tags: ["Wiesn", "Reservierung", "Gruppe"],
    soldOut: false,
    tiers: [
      {
        id: "abendbox",
        name: "Abendbox 10 Personen",
        description: "Ganzer Tisch inklusive zehn Maß und zehn halben Hendl.",
        priceCents: 49000,
        feeCents: 2500,
        available: 7,
      },
    ],
  },
  {
    id: "comedy-mixed-show",
    title: "Quatsch Comedy Mixed Show",
    subtitle: "Fünf Comedians, ein Abend, moderiert",
    description:
      "Fünf Stand-up-Acts aus der aktuellen deutschen Szene, moderiert und mit Zugabenrunde. Line-up wird eine Woche vorher bekannt gegeben.",
    category: "kultur",
    startsAt: "2026-09-11T20:00:00+02:00",
    endsAt: "2026-09-11T22:30:00+02:00",
    doorsAt: "2026-09-11T19:00:00+02:00",
    venue: "Kesselhaus Kulturbrauerei",
    city: "Berlin",
    address: "Schönhauser Allee 36, 10435 Berlin",
    organizer: "Quatsch Comedy Club",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Comedian mit Mikrofon auf kleiner Bühne",
    tags: ["Comedy", "Stand-up", "Mixed Show"],
    soldOut: false,
    tiers: [
      {
        id: "stehplatz",
        name: "Stehplatz",
        description: "Freie Platzwahl im hinteren Saalbereich.",
        priceCents: 2400,
        feeCents: 250,
        available: 120,
      },
      {
        id: "sitzplatz",
        name: "Sitzplatz vorne",
        description: "Nummerierter Stuhl in den Reihen 1–8.",
        priceCents: 3600,
        feeCents: 320,
        available: 44,
      },
    ],
  },
  {
    id: "reise-lissabon-staedtetrip",
    title: "Städtetrip Lissabon",
    subtitle: "4 Tage Altstadt, Fado und Tagesausflug nach Sintra",
    description:
      "Flug ab Berlin, drei Nächte im Boutiquehotel in der Baixa, geführter Rundgang durch Alfama mit Fado-Abend sowie ein Tagesausflug nach Sintra mit Bahnticket.",
    category: "reisen",
    startsAt: "2026-10-08T07:30:00+02:00",
    endsAt: "2026-10-11T22:00:00+02:00",
    doorsAt: "2026-10-08T05:30:00+02:00",
    venue: "Abflug Berlin Brandenburg",
    city: "Lissabon",
    address: "Flughafen BER, Terminal 1, 12529 Schönefeld",
    organizer: "Eventoren Reisen",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Straßenbahn in einer engen Altstadtgasse",
    tags: ["Reise", "Städtetrip", "Flug inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "doppel",
        name: "Doppelzimmer pro Person",
        description: "Drei Nächte im Doppelzimmer inklusive Frühstück.",
        priceCents: 64900,
        feeCents: 2900,
        available: 16,
      },
      {
        id: "einzel",
        name: "Einzelzimmer",
        description: "Drei Nächte im Einzelzimmer inklusive Frühstück.",
        priceCents: 79900,
        feeCents: 2900,
        available: 5,
      },
    ],
  },
  {
    id: "weihnachtsmarkt-nuernberg-fuehrung",
    title: "Christkindlesmarkt — Abendführung",
    subtitle: "90 Minuten Geschichte, Glühwein und Lebkuchen",
    description:
      "Geführter Rundgang über den Nürnberger Christkindlesmarkt mit Stationen bei einer Lebkuchenbäckerei und einer Zinnfigurenwerkstatt. Ein Glühwein ist inklusive.",
    category: "kultur",
    startsAt: "2026-12-05T17:30:00+01:00",
    endsAt: "2026-12-05T19:00:00+01:00",
    doorsAt: "2026-12-05T17:15:00+01:00",
    venue: "Hauptmarkt",
    city: "Nürnberg",
    address: "Hauptmarkt 18, 90403 Nürnberg",
    organizer: "Nürnberg Tourismus",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Beleuchtete Weihnachtsmarktbuden",
    tags: ["Weihnachtsmarkt", "Führung", "Glühwein inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "fuehrung",
        name: "Führung inkl. Glühwein",
        description: "Rundgang in Kleingruppe mit einem Heißgetränk.",
        priceCents: 1900,
        feeCents: 150,
        available: 22,
      },
    ],
  },
  {
    id: "silvester-tanz-in-den-jahreswechsel",
    title: "Silvesterball im Kurhaus",
    subtitle: "Big Band, Menü und Mitternachtsfeuerwerk",
    description:
      "Viergängiges Menü ab 19 Uhr, danach Tanz mit der 17-köpfigen Hausbigband. Um Mitternacht Sekt auf der Terrasse mit Blick auf das Feuerwerk.",
    category: "kultur",
    startsAt: "2026-12-31T19:00:00+01:00",
    endsAt: "2027-01-01T03:00:00+01:00",
    doorsAt: "2026-12-31T18:15:00+01:00",
    venue: "Kurhaus Wiesbaden",
    city: "Wiesbaden",
    address: "Kurhausplatz 1, 65189 Wiesbaden",
    organizer: "Kurhaus Wiesbaden Betriebsgesellschaft",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Festlicher Ballsaal mit Kronleuchtern",
    tags: ["Silvester", "Ball", "Menü inklusive"],
    soldOut: false,
    tiers: [
      {
        id: "ball-standard",
        name: "Ballkarte mit Menü",
        description: "Sitzplatz im Saal, Viergangmenü und Mitternachtssekt.",
        priceCents: 18500,
        feeCents: 900,
        available: 88,
      },
      {
        id: "ball-loge",
        name: "Logenplatz",
        description: "Reservierte Loge für zwei Personen mit Terrassenzugang.",
        priceCents: 46000,
        feeCents: 1800,
        available: 6,
      },
    ],
  },
  {
    id: "ski-alpin-weltcup-garmisch",
    title: "FIS Ski Weltcup — Abfahrt Kandahar",
    subtitle: "Herrenabfahrt an der Garmischer Kandahar",
    description:
      "Tagesticket für die Herrenabfahrt inklusive Zugang zum Zielstadion und Siegerehrung. Shuttlebusse fahren ab dem Bahnhof Garmisch-Partenkirchen im 15-Minuten-Takt.",
    category: "sport",
    startsAt: "2027-01-30T11:30:00+01:00",
    endsAt: "2027-01-30T15:00:00+01:00",
    doorsAt: "2027-01-30T08:30:00+01:00",
    venue: "Kandahar-Zielstadion",
    city: "Garmisch-Partenkirchen",
    address: "Am Kreuzeckbahnhof 12, 82467 Garmisch-Partenkirchen",
    organizer: "SC Riessersee e.V.",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Skirennläufer im Zielhang vor Zuschauern",
    tags: ["Ski", "Weltcup", "Shuttle"],
    soldOut: false,
    tiers: [
      {
        id: "stehplatz-ziel",
        name: "Zielstadion Stehplatz",
        description: "Tagesticket mit freier Platzwahl im Zielstadion.",
        priceCents: 4500,
        feeCents: 350,
        available: 420,
      },
      {
        id: "tribuene",
        name: "Zieltribüne Sitzplatz",
        description: "Nummerierter Sitzplatz mit Blick auf den Zieleinlauf.",
        priceCents: 9800,
        feeCents: 600,
        available: 48,
      },
    ],
  },
  {
    id: "rock-am-ring-2027",
    title: "Rock am Ring 2027",
    subtitle: "Drei Tage Rock am Nürburgring",
    description:
      "Vier Bühnen, über 80 Bands und Camping direkt am Ring. Das Ticket gilt für alle drei Tage, Anreise ist ab Mittwochmittag möglich.",
    category: "festivals",
    startsAt: "2027-06-04T12:00:00+02:00",
    endsAt: "2027-06-06T23:59:00+02:00",
    doorsAt: "2027-06-03T12:00:00+02:00",
    venue: "Nürburgring",
    city: "Nürburg",
    address: "Otto-Flimm-Straße, 53520 Nürburg",
    organizer: "eventim live",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Große Festivalbühne mit Publikum",
    tags: ["Rock", "Camping", "3 Tage"],
    soldOut: false,
    tiers: [
      {
        id: "festival-camping",
        name: "Festivalticket inkl. Camping",
        description: "Alle drei Tage plus Stellplatz auf dem Standardcamping.",
        priceCents: 27900,
        feeCents: 1700,
        available: 540,
      },
      {
        id: "green-camping",
        name: "Green Camping",
        description: "Ruhigeres Camping mit Pfandsystem und Sanitärzugang.",
        priceCents: 33900,
        feeCents: 1900,
        available: 60,
      },
    ],
  },
  {
    id: "tatort-lesung-hafenkrimi",
    title: "Krimilesung an Bord",
    subtitle: "Nordseekrimi auf einem historischen Frachtsegler",
    description:
      "Zweistündige Lesung an Deck eines restaurierten Frachtseglers im Museumshafen, begleitet von Seemannsliedern. Warme Kleidung wird empfohlen.",
    category: "kultur",
    startsAt: "2026-09-18T19:00:00+02:00",
    endsAt: "2026-09-18T21:00:00+02:00",
    doorsAt: "2026-09-18T18:30:00+02:00",
    venue: "Museumshafen Oevelgönne",
    city: "Hamburg",
    address: "Neumühlen 25, 22763 Hamburg",
    organizer: "Literaturhaus Hamburg",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Historisches Segelschiff im Hafen",
    tags: ["Lesung", "Krimi", "Kleines Publikum"],
    soldOut: true,
    tiers: [
      {
        id: "deckplatz",
        name: "Deckplatz",
        description: "Sitzplatz an Deck, Decken werden gestellt.",
        priceCents: 2800,
        feeCents: 220,
        available: 0,
      },
    ],
  },
  {
    id: "reise-wandern-suedtirol",
    title: "Wanderwoche Südtirol",
    subtitle: "7 Tage Dolomiten mit Bergführer",
    description:
      "Sechs geführte Tagesetappen rund um die Seiser Alm, Gepäcktransport zwischen den Hütten und Halbpension. Für Einsteiger mit Grundkondition geeignet.",
    category: "reisen",
    startsAt: "2027-07-10T09:00:00+02:00",
    endsAt: "2027-07-16T17:00:00+02:00",
    doorsAt: "2027-07-10T08:00:00+02:00",
    venue: "Treffpunkt Bahnhof Bozen",
    city: "Kastelruth",
    address: "Bahnhofsplatz 1, 39100 Bozen, Italien",
    organizer: "Eventoren Reisen",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Wanderweg vor Dolomitengipfeln",
    tags: ["Reise", "Wandern", "Bergführer"],
    soldOut: false,
    tiers: [
      {
        id: "huettenlager",
        name: "Hüttenlager",
        description: "Sechs Nächte im Mehrbettlager mit Halbpension.",
        priceCents: 89000,
        feeCents: 3500,
        available: 11,
      },
      {
        id: "huetten-doppel",
        name: "Doppelzimmer",
        description: "Sechs Nächte im Doppelzimmer mit Halbpension.",
        priceCents: 118000,
        feeCents: 3500,
        available: 4,
      },
    ],
  },
  {
    id: "arena-tour-annenmaykantereit",
    title: "AnnenMayKantereit — Arenatour",
    subtitle: "Neue Songs und alte Hits, mit Streicherensemble",
    description:
      "Die Kölner Band spielt ein zweistündiges Set mit vierköpfigem Streicherensemble. Der Innenraum ist unbestuhlt, Rollstuhlplätze sind über den Service buchbar.",
    category: "konzerte",
    startsAt: "2026-11-07T20:00:00+01:00",
    endsAt: "2026-11-07T22:30:00+01:00",
    doorsAt: "2026-11-07T18:30:00+01:00",
    venue: "Lanxess Arena",
    city: "Köln",
    address: "Willy-Brandt-Platz 3, 50679 Köln",
    organizer: "Live Nation GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Bandauftritt in einer großen Arena",
    tags: ["Pop", "Deutschsprachig", "Streicher"],
    soldOut: false,
    tiers: [
      {
        id: "innenraum-steh",
        name: "Innenraum Stehplatz",
        description: "Unbestuhlter Innenraum, freie Platzwahl.",
        priceCents: 5900,
        feeCents: 590,
        available: 320,
      },
      {
        id: "unterrang",
        name: "Unterrang Sitzplatz",
        description: "Nummerierter Sitzplatz mit direkter Bühnensicht.",
        priceCents: 7400,
        feeCents: 640,
        available: 96,
      },
      {
        id: "oberrang-seitlich",
        name: "Oberrang seitlich",
        description: "Günstiger Sitzplatz mit teilweise seitlicher Sicht.",
        priceCents: 4200,
        feeCents: 420,
        available: 180,
      },
    ],
  },
  {
    id: "basketball-euroleague-bayern",
    title: "FC Bayern Basketball — Real Madrid",
    subtitle: "EuroLeague-Hauptrunde im SAP Garden",
    description:
      "Europäisches Spitzenbasketball im neuen SAP Garden. Halleneinlass zwei Stunden vor Tip-off, im Innenraum gilt ein Taschenlimit von DIN A4.",
    category: "sport",
    startsAt: "2026-10-29T20:30:00+01:00",
    endsAt: "2026-10-29T22:30:00+01:00",
    doorsAt: "2026-10-29T18:30:00+01:00",
    venue: "SAP Garden",
    city: "München",
    address: "Toni-Merkens-Weg 1, 80809 München",
    organizer: "FC Bayern München Basketball GmbH",
    imageUrl: eventImagePlaceholder,
    imageAlt: "Basketballfeld mit Anzeigetafel",
    tags: ["Basketball", "EuroLeague", "Taschenlimit"],
    soldOut: false,
    tiers: [
      {
        id: "oberrang-basket",
        name: "Oberrang",
        description: "Nummerierter Sitzplatz im oberen Rang.",
        priceCents: 2900,
        feeCents: 250,
        available: 340,
      },
      {
        id: "courtside",
        name: "Courtside",
        description: "Erste Reihe am Spielfeldrand inkl. Catering.",
        priceCents: 24500,
        feeCents: 1200,
        available: 8,
      },
    ],
  },
]
