export type OrganizerText = {
  readonly area: string
  readonly eventsTitle: string
  readonly eventsDescription: string
  readonly noEvents: string
  readonly eventOpen: string
  readonly tickets: string
  readonly ticketsDescription: string
  readonly back: string
  readonly searchLabel: string
  readonly searchPlaceholder: string
  readonly noTickets: string
  readonly selectTicket: string
  readonly ticketNumber: string
  readonly participant: string
  readonly participantFallback: string
  readonly buyer: string
  readonly buyerEmail: string
  readonly price: string
  readonly paid: string
  readonly unpaid: string
  readonly cancelled: string
  readonly valid: string
  readonly checkedIn: string
  readonly notCheckedIn: string
  readonly checkedInAt: string
  readonly operator: string
  readonly checkIn: string
  readonly reset: string
  readonly working: string
  readonly loading: string
  readonly loadMore: string
  readonly loadError: string
  readonly actionSuccess: string
  readonly resetSuccess: string
  readonly duplicateTitle: string
  readonly unauthorized: string
  readonly wrongEvent: string
  readonly unknownTicket: string
  readonly actionFailed: string
  readonly elapsed: string
  readonly unknown: string
  readonly scannerTitle: string
  readonly scannerDescription: string
  readonly scannerStart: string
  readonly scannerStop: string
  readonly scannerStarting: string
  readonly scannerActive: string
  readonly scannerCheckingIn: string
  readonly scannerPermissionDenied: string
  readonly scannerUnavailable: string
  readonly scannerInUse: string
  readonly scannerSecureContext: string
  readonly scannerError: string
  readonly scanSuccess: string
}
