import type { OrganizerText } from "./OrganizerText.ts"

export function organizerTextGet(): OrganizerText {
  return {
    area: "Veranstalter",
    eventsTitle: "Deine Events",
    eventsDescription: "Wähle ein Event aus, um Tickets zu suchen und Gäste einzuchecken.",
    noEvents: "Für deinen Zugriffszeitraum sind keine Events verfügbar.",
    eventOpen: "Ticketliste öffnen",
    tickets: "Tickets",
    ticketsDescription: "Suche nach Teilnehmer- oder Käufername und wähle ein Ticket aus.",
    back: "Zur Eventübersicht",
    searchLabel: "Tickets durchsuchen",
    searchPlaceholder: "Teilnehmer- oder Käufername",
    noTickets: "Keine passenden Tickets gefunden.",
    selectTicket: "Wähle ein Ticket aus der Liste, um die Details zu sehen.",
    ticketNumber: "Ticketnummer",
    participant: "Teilnehmername",
    participantFallback: "Käufer als Ersatz (kein Teilnehmername vorhanden)",
    buyer: "Käufer",
    buyerEmail: "Käufer-E-Mail",
    price: "Preis",
    paid: "Bezahlt",
    unpaid: "Nicht bezahlt",
    cancelled: "Storniert",
    valid: "Nicht storniert",
    checkedIn: "Eingecheckt",
    notCheckedIn: "Nicht eingecheckt",
    checkedInAt: "Check-in-Zeitpunkt",
    operator: "Ausgeführt von",
    checkIn: "Jetzt einchecken",
    reset: "Check-in zurücksetzen (Test)",
    working: "Wird ausgeführt …",
    loading: "Wird geladen …",
    loadMore: "Weitere Tickets laden",
    loadError: "Die Veranstalterdaten konnten nicht geladen werden.",
    actionSuccess: "Ticket wurde eingecheckt.",
    resetSuccess: "Check-in wurde zurückgesetzt.",
    duplicateTitle: "Dieses Ticket wurde bereits eingecheckt.",
    unauthorized: "Du bist für dieses Event nicht berechtigt.",
    wrongEvent: "Dieses Ticket gehört zu einem anderen Event.",
    unknownTicket: "Das Ticket wurde nicht gefunden.",
    actionFailed: "Die Aktion konnte nicht ausgeführt werden.",
    elapsed: "Vergangene Zeit",
    unknown: "Unbekannt",
    scannerTitle: "QR-Code scannen",
    scannerDescription:
      "Scanne den QR-Code eines einzelnen Tickets. Der Check-in wird erst nach der atomaren Serverbestätigung ausgelöst.",
    scannerStart: "Kamera starten",
    scannerStop: "Kamera stoppen",
    scannerStarting: "Kamera wird gestartet …",
    scannerActive: "Kamera ist aktiv. Halte einen Ticket-QR-Code vor die Kamera.",
    scannerCheckingIn: "Ticket wird geprüft …",
    scannerPermissionDenied:
      "Die Kameraberechtigung wurde verweigert. Erlaube den Kamerazugriff in den Browsereinstellungen oder nutze den manuellen Check-in.",
    scannerUnavailable: "Keine passende Kamera gefunden. Nutze den manuellen Check-in.",
    scannerInUse: "Die Kamera wird bereits von einer anderen Anwendung verwendet.",
    scannerSecureContext: "Der Kamerazugriff benötigt eine sichere Verbindung (HTTPS).",
    scannerError: "Die Kamera konnte nicht gestartet werden. Nutze den manuellen Check-in.",
    scanSuccess: "QR-Code bestätigt: Ticket wurde eingecheckt.",
  }
}
