import type { Language } from "../app/i18n/language.ts"
import type { OrganizerText } from "./OrganizerText.ts"

export function organizerTextGet(language: Language): OrganizerText {
  if (language === "de") {
    return {
      area: "Veranstalter",
      eventsTitle: "Deine Events",
      eventsDescription: "Wähle ein Event aus, um Tickets zu suchen und Gäste einzuchecken.",
      noEvents: "Für deinen Zugriffszeitraum sind keine Events verfügbar.",
      eventOpen: "Ticketliste öffnen",
      tickets: "Tickets",
      ticketsDescription: "Suche nach Teilnehmer- oder Käufername und wähle ein Ticket aus.",
      back: "Zur Eventübersicht",
      searchLabel: "Tickets durchsuchen",
      searchPlaceholder: "Teilnehmer- oder Käufername",
      noTickets: "Keine passenden Tickets gefunden.",
      selectTicket: "Wähle ein Ticket aus der Liste, um die Details zu sehen.",
      ticketNumber: "Ticketnummer",
      participant: "Teilnehmername",
      participantFallback: "Käufer als Ersatz (kein Teilnehmername vorhanden)",
      buyer: "Käufer",
      buyerEmail: "Käufer-E-Mail",
      price: "Preis",
      paid: "Bezahlt",
      unpaid: "Nicht bezahlt",
      cancelled: "Storniert",
      valid: "Nicht storniert",
      checkedIn: "Eingecheckt",
      notCheckedIn: "Nicht eingecheckt",
      checkedInAt: "Check-in-Zeitpunkt",
      operator: "Ausgeführt von",
      checkIn: "Jetzt einchecken",
      reset: "Check-in zurücksetzen (Test)",
      working: "Wird ausgeführt …",
      loading: "Wird geladen …",
      loadMore: "Weitere Tickets laden",
      loadError: "Die Veranstalterdaten konnten nicht geladen werden.",
      actionSuccess: "Ticket wurde eingecheckt.",
      resetSuccess: "Check-in wurde zurückgesetzt.",
      duplicateTitle: "Dieses Ticket wurde bereits eingecheckt.",
      unauthorized: "Du bist für dieses Event nicht berechtigt.",
      wrongEvent: "Dieses Ticket gehört zu einem anderen Event.",
      unknownTicket: "Das Ticket wurde nicht gefunden.",
      actionFailed: "Die Aktion konnte nicht ausgeführt werden.",
      elapsed: "Vergangene Zeit",
      unknown: "Unbekannt",
      scannerTitle: "QR-Code scannen",
      scannerDescription:
        "Scanne den QR-Code eines einzelnen Tickets. Der Check-in wird erst nach der atomaren Serverbestätigung ausgelöst.",
      scannerStart: "Kamera starten",
      scannerStop: "Kamera stoppen",
      scannerStarting: "Kamera wird gestartet …",
      scannerActive: "Kamera ist aktiv. Halte einen Ticket-QR-Code vor die Kamera.",
      scannerCheckingIn: "Ticket wird geprüft …",
      scannerPermissionDenied:
        "Die Kameraberechtigung wurde verweigert. Erlaube den Kamerazugriff in den Browsereinstellungen oder nutze den manuellen Check-in.",
      scannerUnavailable: "Keine passende Kamera gefunden. Nutze den manuellen Check-in.",
      scannerInUse: "Die Kamera wird bereits von einer anderen Anwendung verwendet.",
      scannerSecureContext: "Der Kamerazugriff benötigt eine sichere Verbindung (HTTPS).",
      scannerError: "Die Kamera konnte nicht gestartet werden. Nutze den manuellen Check-in.",
      scanSuccess: "QR-Code bestätigt: Ticket wurde eingecheckt.",
    }
  }
  return {
    area: "Organizer",
    eventsTitle: "Your events",
    eventsDescription: "Choose an event to search tickets and check in guests.",
    noEvents: "No events are available for your access period.",
    eventOpen: "Open ticket list",
    tickets: "Tickets",
    ticketsDescription: "Search by participant or buyer name and select a ticket.",
    back: "Back to events",
    searchLabel: "Search tickets",
    searchPlaceholder: "Participant or buyer name",
    noTickets: "No matching tickets found.",
    selectTicket: "Select a ticket from the list to see its details.",
    ticketNumber: "Ticket number",
    participant: "Participant name",
    participantFallback: "Buyer used as fallback (no participant name available)",
    buyer: "Buyer",
    buyerEmail: "Buyer email",
    price: "Price",
    paid: "Paid",
    unpaid: "Unpaid",
    cancelled: "Cancelled",
    valid: "Not cancelled",
    checkedIn: "Checked in",
    notCheckedIn: "Not checked in",
    checkedInAt: "Check-in time",
    operator: "Checked in by",
    checkIn: "Check in now",
    reset: "Reset check-in (test)",
    working: "Working …",
    loading: "Loading …",
    loadMore: "Load more tickets",
    loadError: "The organizer data could not be loaded.",
    actionSuccess: "Ticket checked in.",
    resetSuccess: "Check-in reset.",
    duplicateTitle: "This ticket has already been checked in.",
    unauthorized: "You are not authorized for this event.",
    wrongEvent: "This ticket belongs to another event.",
    unknownTicket: "The ticket was not found.",
    actionFailed: "The action could not be completed.",
    elapsed: "Elapsed time",
    unknown: "Unknown",
    scannerTitle: "Scan QR code",
    scannerDescription: "Scan the QR code of one ticket. Check-in starts only after atomic server confirmation.",
    scannerStart: "Start camera",
    scannerStop: "Stop camera",
    scannerStarting: "Starting camera …",
    scannerActive: "Camera is active. Hold a ticket QR code in front of the camera.",
    scannerCheckingIn: "Checking ticket …",
    scannerPermissionDenied:
      "Camera permission was denied. Allow camera access in your browser settings or use manual check-in.",
    scannerUnavailable: "No suitable camera was found. Use manual check-in.",
    scannerInUse: "The camera is already being used by another application.",
    scannerSecureContext: "Camera access requires a secure connection (HTTPS).",
    scannerError: "The camera could not be started. Use manual check-in.",
    scanSuccess: "QR code confirmed: ticket checked in.",
  }
}
